package adsim;

import lombok.experimental.Value;

/**
 * 2D Vector class.
 * - Immutable Object
 */
@Value
public class Vector {
	// Fields, getters etc. will be generated by lombok.
	double x;
	double y;
	
	public Vector add(Vector other){
		return new Vector(this.getX() + other.getX(), this.getY() + other.getY());
	}
	
	public static final Vector zero = new Vector(0, 0);
}
